routes/admin.php
<?php
/**
 * Created by PhpStorm.
 * User: Lukas Figura
 * Date: 21/02/2017
 * Time: 17:58
 */

Route::group(['middleware' => 'auth','admin'], function () {
	
	Route::get('/', 'Admin\AdminController@index');
	
	Route::resource('users', 'Admin\UsersController');
	
	Route::resource('answers', 'Admin\AnswerController');

	Route::get('questions', 'Admin\QuestionController@index');
    Route::get('questions/create', 'Admin\QuestionController@create');
    Route::get('questions/{id}/edit', 'Admin\QuestionController@edit');
    Route::post('questions/{id}/update', 'Admin\QuestionController@update');
    Route::post('questions', 'Admin\QuestionController@store');

    Route::get('games/{id}', 'Admin\GameController@show');

    Route::resource('options', 'Admin\OptionController');
	
	Route::resource('funfacts', 'Admin\FunfactController');

	Route::get('ranking', 'Admin\RankController@index');
	
	
});

routes/web.php
<?php

Route::get('/', function () {
	return view('welcome');
});

// Authentication Routes...
$this->get('login/admin', 'Auth\LoginController@showLoginForm')->name('login');
$this->post('login/admin', 'Auth\LoginController@login');
$this->post('logout', 'Auth\LoginController@logout')->name('logout');

// Auth social
$this->get('login/facebook', 'Auth\LoginController@redirectToFacebookProvider');
$this->get('auth/login/facebook/callback', 'Auth\LoginController@handleFacebookProviderCallback');

$this->get('login/google', 'Auth\LoginController@redirectToGoogleProvider');
$this->get('auth/login/google/callback', 'Auth\LoginController@handleGoogleProviderCallback');


// Registration Routes...
$this->get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
$this->post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
$this->get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
$this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
$this->get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
$this->post('password/reset', 'Auth\ResetPasswordController@reset');

$this->get('/home', 'HomeController@index')->name('home');

$this->get('/game', 'GameController@index')->name('game');
$this->post('/game/answer', 'GameController@storeAnswer')->name('gameAnswerStore');
$this->get('/game/video', 'GameController@video');

$this->get('/login', 'Auth\LoginController@loginClient');


// Result game Routes...
$this->get('/result/highscore', 'ResultController@highscore');

app/Models/Game.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Game extends Model
{
    protected $table = 'games';

    protected $fillable = [
        'user_id',
        'token',
    ];

    public function getTimeAttribute()
    {
        return $this->answers()->sum('time');
    }

    public function getPointsAttribute()
    {
        return $this->answers->filter(function ($answer) {
            return $answer->correct;
        })->count();
    }

    public function getRankAttribute()
    {
        $gamesSorted = Game::all()
            ->sortByDesc(function ($game) {
                return $game->points;
            });

        foreach ($gamesSorted as $index => $game) {
            if ($game->id == $this->id) {
                return $index + 1;
            }
        }

        return 1;
    }

    public function user()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function answers()
    {
        return $this->hasMany(Answer::class);
    }

    public function completed()
    {
        foreach (Level::get() as $level) {
            if (!$this->answers()->whereHas('question', function ($q) use ($level) {
                $q->where('level_id', $level->id);
            })->exists()) return false;
        }

        return true;
    }

    public function progress()
    {
        $percent = 0;
        $percentPart = 100 / Level::get()->count();
        foreach (Level::orderBy('id', 'asc')->get() as $level) {
            if (!$this->answers()->whereHas('question', function ($q) use ($level) {
                $q->where('level_id', $level->id);
            })->exists()) break;

            $percent += $percentPart;
        }

        return $percent;
    }

    public function scopeToday($query)
    {
        return $query->where('created_at', '>=', Carbon::today());
    }
}

app/Http/Controllers/Admin/GameController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Game;
use Illuminate\Http\Request;

class GameController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $game = Game::findOrFail($id);

        return view('admin.games.show', compact('game'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/GameController.php
<?php

namespace App\Http\Controllers;

use App\Models\Answer;
use App\Models\Game;
use Closure;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Session;

class GameController extends Controller
{
	
	/**
	 * GameController constructor.
	 */
	public function __construct()
	{
		$this->middleware(function ($request, Closure $next) {
			if (!Auth::check()) {
				return redirect()->action('Auth\LoginController@loginClient');
			} else {
				return $next($request);
			}
		});
	}
	
	public function index()
	{
//		if (!Session::has('game_token')) {
			
			$game = Game::create([
				'user_id' => Auth::id(),
				'token'   => uniqid(),
			]);
			
			Session::put('game_token', $game->token);
//		} else {
//			$resume = true;
//			$game = Game::where('token', Session::get('game_token'))->first();
//
//			if ($game->completed()) {
//
//			} else {
//
//			}
//
//		}
		
		return view('game.index');
	}
	
	public function storeAnswer( Request $request )
	{
		$this->validate($request, [
			'question_id' => 'required|exists:questions,id',
			'option_id'   => 'required|exists:options,id',
			'time'        => 'required',
		]);
		
		$game = Game::where('token', Session::get('game_token'))->first();
		
		$answer = Answer::create([
			'user_id'     => Auth::id(),
			'option_id'   => $request->option_id,
			'question_id' => $request->question_id,
			'game_id'     => $game->id,
			'time'        => number_format($request->time / 1000,3,'.',''),
		]);
		
		return response('ok');
	}

    public function video()
    {
        return view('game.video');
	}
}

resources/views/admin/games/create.blade.php
@extends('layouts.admin')


@section('content')
    {!! Form::open(['action'=>'Admin\UsersController@store', 'method'=>'POST','class'=>'form-horizontal']) !!}


    @include('admin.partials.formButtons')


    <div class="row">
        @include('admin.partials.formErrors')

        <div class="col-lg-7">
            <div class="box">
                <div class="box-header simple">
                    Všeobecné nastavenia
                </div>
                <div class="box-body">
                    <div class="form-group">
                        {!! Form::label('name', 'Meno:', ['class'=>'col-sm-4 control-label']) !!}
                        <div class="col-sm-8">
                            {!! Form::text('name', null, ['class'=>'form-control','placeholder'=>'Meno a priezvisko']) !!}
                        </div>
                    </div>
                    <div class="form-group">
                        {!! Form::label('email', 'E-mail:', ['class'=>'col-sm-4 control-label']) !!}
                        <div class="col-sm-8">
                            {!! Form::email('email', null, ['class'=>'form-control','placeholder'=>'E-mail']) !!}
                        </div>
                    </div>
                </div>
            </div>

        </div>

        <div class="col-lg-5">
            <div class="box">
                <div class="box-header simple">
                    Heslo
                </div>
                <div class="box-body">
                    <div class="form-group">
                        {!! Form::label('password', 'Heslo:', ['class'=>'col-sm-4 control-label']) !!}
                        <div class="col-sm-8">
                            {!! Form::password('password', ['class'=>'form-control','placeholder'=>'Heslo']) !!}
                        </div>
                    </div>
                    <div class="form-group">
                        {!! Form::label('password_confirmation', 'Heslo znova:', ['class'=>'col-sm-4 control-label']) !!}
                        <div class="col-sm-8">
                            {!! Form::password('password_confirmation', ['class'=>'form-control','placeholder'=>'Heslo znova']) !!}
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
    {!! Form::close() !!}
@endsection

@section('scripts')

@endsection

resources/views/admin/games/edit.blade.php
@extends('layouts.admin')

@section('content')

    {!! Form::open(['action'=>['Admin\UsersController@update', $user->id], 'method'=>'PATCH','class'=>'form-horizontal']) !!}


    @include('admin.partials.formButtons')


    <div class="row">
        @include('admin.partials.formErrors')

        <div class="col-lg-6">

            <div class="box">
                <div class="box-header simple">
                    General
                </div>
                <div class="box-body">
                    <div class="form-group">
                        {!! Form::hidden('old_email', $user->email) !!}
                        {!! Form::label('name', 'Name:', ['class'=>'col-sm-4 control-label']) !!}
                        <div class="col-sm-8">
                            {!! Form::text('name', $user->name, ['class'=>'form-control','placeholder'=>'Name']) !!}
                        </div>
                    </div>
                    <div class="form-group">
                        {!! Form::label('email', 'E-mail:', ['class'=>'col-sm-4 control-label']) !!}
                        <div class="col-sm-8">
                            {!! Form::email('email', $user->email, ['class'=>'form-control','placeholder'=>'E-mail']) !!}
                        </div>
                    </div>
                </div>
            </div>

        </div>

        <div class="col-lg-6">
            <div class="box">
                <div class="box-header simple">
                    Password
                </div>
                <div class="box-body">
                    <div class="form-group">
                        {!! Form::label('password', 'New password:', ['class'=>'col-sm-4 control-label']) !!}
                        <div class="col-sm-8">
                            {!! Form::password('password', ['class'=>'form-control','placeholder'=>'']) !!}
                        </div>
                    </div>
                    <div class="form-group">
                        {!! Form::label('password_confirmation', 'Confirm password:', ['class'=>'col-sm-4 control-label']) !!}
                        <div class="col-sm-8">
                            {!! Form::password('password_confirmation', ['class'=>'form-control','placeholder'=>'']) !!}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {!! Form::close() !!}
@endsection

@section('scripts')

@endsection

resources/views/admin/games/index.blade.php
@extends('layouts.admin')

@section('content')


    <div class="row">
        <div class="col-lg-12">
            <div class="box">
                <div class="box-header simple">
                    All users
                    <div class="pull-right">
                        <a href="{{action('Admin\UsersController@create')}}"
                           class="btn btn-sm btn-default"><i class="fa fa-plus"></i> Create</a>
                    </div>
                </div>
                <div class="box-body">
                    <table class="table table-striped table-bordered table-hover">
                        <thead>
                        <tr>
                            <th>
                                <p>Full name</p>
                            </th>
                            <th>Email</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($users as $user)
                            <tr>
                                <td>
                                    {{$user->name}} {{$user->surname}}
                                </td>
                                <td>
                                    {{$user->email}}
                                </td>
                                <td class="table-btn-column">

                                    <a href="{{ action('Admin\UsersController@show', $user->id) }}"
                                       class="btn btn-sm btn-primary">
                                        Show
                                    </a>

                                    <a class="btn btn-sm btn-default"
                                       href="{{action('Admin\UsersController@edit',$user->id)}}">
                                        <i class="fa fa-wrench"></i> Edit
                                    </a>

                                    <a href="{{$user->id}}" data-itemname="{{$user->name}}"
                                       class="btn btn-sm btn-danger btn-delete">
                                        <i class="fa fa-trash"></i> Delete
                                    </a>

                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                    {!! $users->render() !!}

                </div>
            </div>
        </div>

    </div>
@endsection

@section('scripts')
    <script>

        var deleteText = "Potvrdením vymažete uživateľa: ";
        var deletedText = "Užívateľ bol úspešne zmazaný.";

    </script>
    {!! Form::open(array('action' => array('Admin\UsersController@index'), 'method' => 'delete', 'class'=>'form-delete', 'id'=>'formDelete')) !!}
    {!! csrf_field() !!}
    {!! Form::close() !!}
@endsection

resources/views/admin/games/show.blade.php
@extends('layouts.admin')

@section('content')

    <div class="pull-right">
        <a class="btn btn-default" href="{{ action('Admin\UsersController@show', $game->user_id) }}">Back</a>
    </div>

    <div class="row">

        <div class="col-lg-6">

            <div class="box">
                <div class="box-header with-border">
                    General
                </div>
                <div class="box-body">
                    <div class="row">
                        <label class="col-sm-4 control-label">User</label>
                        <div class="col-sm-8">
                            {{ $game->user->email }}
                        </div>
                    </div>
                    <div class="row">
                        <label class="col-sm-4 control-label">Token</label>
                        <div class="col-sm-8">
                            {{ $game->token }}
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>

    <div class="row">

        <div class="col-lg-6">

            <div class="box">
                <div class="box-header with-border">
                    Statistics
                </div>
                <div class="box-body">
                    <div class="row">
                        <label class="col-sm-4 control-label">Points</label>
                        <div class="col-sm-8">
                            {{ $game->points }}
                        </div>
                    </div>
                    <div class="row">
                        <label class="col-sm-4 control-label">Total time</label>
                        <div class="col-sm-8">
                            {{ $game->time . ' seconds' }}
                        </div>
                    </div>
                    <div class="row">
                        <label class="col-sm-4 control-label">Rank</label>
                        <div class="col-sm-8">
                            {{ $game->rank }}
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>

    <div class="row">

        <div class="col-lg-12">
            <div class="box">
                <div class="box-header simple">
                    Answers
                </div>
                <div class="box-body">
                    <table class="table table-striped table-bordered table-hover">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>Level</th>
                            <th>Question</th>
                            <th>Answer</th>
                            <th>Time spent (s)</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($game->answers as $answer)
                            <tr>
                                <td>
                                    {{ $loop->iteration }}
                                </td>
                                <td>{{ $answer->question->level->name }}</td>
                                <td>{{ $answer->question->content }}</td>
                                <td><span class="answer {{ $answer->correct ? '' : 'answer--incorrect' }}">{{ $answer->option->content }}</span></td>
                                <td>{{ $answer->time }}</td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

    </div>

@endsection

@section('scripts')

@endsection